export const SET_USER_COORDINATES = "SET_USER_COORDINATES";
export const SET_WEATHER_DATA = "SET_WEATHER_DATA";
export const SET_DAILY_FORECAST = "SET_DAILY_FORECAST";
export const SET_WEEKLY_FORECAST = "SET_WEEKLY_FORECAST";
export const SET_CURRENT_WEATHER = "SET_CURRENT_WEATHER";
export const SET_USER_OPTIONS = "SET_USER_OPTIONS";
